import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="layout">
          {/* Sidebar placeholder, to be filled with roles/categories */}
          <aside className="sidebar">
            <div className="sidebar-title">Prompt Library</div>
            {/* Sidebar content will be injected here by the main page */}
          </aside>
          <div className="main-content">{children}</div>
        </div>
      </body>
    </html>
  );
}
